name: Crypto News 24h

on:
  schedule:
    - cron: "0 * * * *"   # chạy mỗi giờ (UTC)
  workflow_dispatch:       # có thể chạy thủ công

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate report
        run: python scripts/generate_report.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add reports README.md
          git commit -m "Auto: update crypto news (24h)" || echo "No changes"
          git push
